### ISSUE TITLE
Nullpointer exception when a property is not in the map

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/neo4j2owl#10]
```
6/03/2020 16:03:27ebi.spot.neo4j2owl.N2OException: Node with key 228019 not in map! This can happen if the node does not have one of the valid base types.
16/03/2020 16:03:27	at ebi.spot.neo4j2owl.N2OEntityManager.getEntity(N2OEntityManager.java:41)
16/03/2020 16:03:27	at ebi.spot.neo4j2owl.OWL2OntologyExporter.createAddAxiom(OWL2OntologyExporter.java:227)
16/03/2020 16:03:27	at ebi.spot.neo4j2owl.OWL2OntologyExporter.addRelation(OWL2OntologyExporter.java:209)
16/03/2020 16:03:27	at ebi.spot.neo4j2owl.OWL2OntologyExporter.exportOWL(OWL2OntologyExporter.java:169)
16/03/2020 16:03:27	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
16/03/2020 16:03:27	at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler$ReflectiveProcedure.apply(ReflectiveProcedureCompiler.java:598)
16/03/2020 16:03:27	at org.neo4j.kernel.impl.proc.ProcedureRegistry.callProcedure(ProcedureRegistry.java:201)
16/03/2020 16:03:27	at org.neo4j.kernel.impl.proc.Procedures.callProcedure(Procedures.java:256)
16/03/2020 16:03:27	at org.neo4j.kernel.impl.api.OperationsFacade.callProcedure(OperationsFacade.java:1440)
16/03/2020 16:03:27	at org.neo4j.kernel.impl.api.OperationsFacade.procedureCallWrite(OperationsFacade.java:1394)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.spi.v3_3.TransactionBoundQueryContext$$anonfun$20.apply(TransactionBoundQueryContext.scala:706)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.spi.v3_3.TransactionBoundQueryContext$$anonfun$20.apply(TransactionBoundQueryContext.scala:706)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.spi.v3_3.TransactionBoundQueryContext.callProcedure(TransactionBoundQueryContext.scala:726)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.spi.v3_3.TransactionBoundQueryContext.callReadWriteProcedure(TransactionBoundQueryContext.scala:707)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext$$anonfun$callReadWriteProcedure$1.apply(ExceptionTranslatingQueryContext.scala:153)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext$$anonfun$callReadWriteProcedure$1.apply(ExceptionTranslatingQueryContext.scala:153)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.spi.v3_3.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:32)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:39)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.spi.v3_3.ExceptionTranslationSupport$class.translateIterator(ExceptionTranslationSupport.scala:45)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext.translateIterator(ExceptionTranslatingQueryContext.scala:39)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.compatibility.v3_3.ExceptionTranslatingQueryContext.callReadWriteProcedure(ExceptionTranslatingQueryContext.scala:153)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.EagerReadWriteCallMode.callProcedure(ProcedureCallMode.scala:55)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.procs.ProcedureExecutionResult.executeCall(ProcedureExecutionResult.scala:69)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.procs.ProcedureExecutionResult.<init>(ProcedureExecutionResult.scala:66)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.procs.ProcedureCallExecutionPlan.createNormalExecutionResult(ProcedureCallExecutionPlan.scala:90)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.compatibility.v3_3.runtime.executionplan.procs.ProcedureCallExecutionPlan.run(ProcedureCallExecutionPlan.scala:80)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$ExecutionPlanWrapper$$anonfun$run$1.apply(Compatibility.scala:183)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$ExecutionPlanWrapper$$anonfun$run$1.apply(Compatibility.scala:179)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.compatibility.v3_3.exceptionHandler$runSafely$.apply(exceptionHandler.scala:90)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.compatibility.v3_3.Compatibility$ExecutionPlanWrapper.run(Compatibility.scala:179)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.PreparedPlanExecution.execute(PreparedPlanExecution.scala:29)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:120)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:112)
16/03/2020 16:03:27	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:76)
16/03/2020 16:03:27	at org.neo4j.server.rest.transactional.TransactionHandle.safelyExecute(TransactionHandle.java:371)
16/03/2020 16:03:27	at org.neo4j.server.rest.transactional.TransactionHandle.executeStatements(TransactionHandle.java:323)
16/03/2020 16:03:27	at org.neo4j.server.rest.transactional.TransactionHandle.commit(TransactionHandle.java:157)
16/03/2020 16:03:27	at org.neo4j.server.rest.web.TransactionalService.lambda$executeStatementsAndCommit$1(TransactionalService.java:218)
16/03/2020 16:03:27	at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
16/03/2020 16:03:27	at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)
16/03/2020 16:03:27	at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
16/03/2020 16:03:27	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
16/03/2020 16:03:27	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
16/03/2020 16:03:27	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
16/03/2020 16:03:27	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
16/03/2020 16:03:27	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
16/03/2020 16:03:27	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
16/03/2020 16:03:27	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
16/03/2020 16:03:27	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
16/03/2020 16:03:27	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
16/03/2020 16:03:27	at org.neo4j.server.rest.dbms.AuthorizationDisabledFilter.doFilter(AuthorizationDisabledFilter.java:49)
16/03/2020 16:03:27	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
16/03/2020 16:03:27	at org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)
16/03/2020 16:03:27	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
16/03/2020 16:03:27	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
16/03/2020 16:03:27	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
16/03/2020 16:03:27	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
16/03/2020 16:03:27	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
16/03/2020 16:03:27	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
16/03/2020 16:03:27	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
16/03/2020 16:03:27	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
16/03/2020 16:03:27	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
16/03/2020 16:03:27	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
16/03/2020 16:03:27	at org.eclipse.jetty.server.Server.handle(Server.java:499)
16/03/2020 16:03:27	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
16/03/2020 16:03:27	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
16/03/2020 16:03:27	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
16/03/2020 16:03:27	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
16/03/2020 16:03:27	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
16/03/2020 16:03:27	at java.lang.Thread.run(Thread.java:748)
16/03/2020 16:03:27Caused by: java.lang.NullPointerException
16/03/2020 16:03:27	... 70 more
16/03/2020 16:03:272020-03-16 16:03:26.936+0000 INFO  234 ms: (planning: 18, cpu: 234, waiting: 0) - 19837672 B - embedded-session
```

**Comment by matentzn** [comment]
Not sure what this was so closing it now. With so little context its worthless.
