### ISSUE TITLE
22 non-unique property safe labels (unqualified) in current KB

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/neo4j2owl#11]
There are 22 properties with non-unique safe-labels (unqualified, like `part_of`) in the KB. 

```
java.lang.IllegalStateException: There are 22 non-unique safe labels (has_quality, gocheck_do_not_annotate, goslim_chembl, goslim_generic, gocheck_do_not_manually_annotate, goslim_pir, goslim_synapse, deprecated, goslim_agr, goslim_plant, goslim_pombe, goslim_candida, goslim_yeast, contains, goslim_metagenomics, exemplar_of, overlaps, goslim_mouse, has_part, member_of, goslim_aspergillus, part_of), pertaining to the following properties: http://purl.obolibrary.org/obo/go#goslim_aspergillus, http://purl.obolibrary.org/obo/fbbt#goslim_pir, http://purl.obolibrary.org/obo/go#goslim_pombe, http://purl.obolibrary.org/obo/fbbt#goslim_pombe, http://purl.obolibrary.org/obo/go#goslim_generic, http://purl.obolibrary.org/obo/fbbt#goslim_aspergillus, http://purl.obolibrary.org/obo/fbbt#gocheck_do_not_annotate, http://purl.obolibrary.org/obo/so#part_of, http://purl.obolibrary.org/obo/RO_0002350, http://purl.obolibrary.org/obo/fbbt#goslim_yeast, http://purl.obolibrary.org/obo/RO_0002131, http://purl.obolibrary.org/obo/RO_0001019, http://purl.obolibrary.org/obo/go#goslim_chembl, http://purl.obolibrary.org/obo/go#goslim_synapse, http://purl.obolibrary.org/obo/c099d9d6-4ef3-11e3-9da7-b1ad5291e0b0, http://purl.obolibrary.org/obo/fbbt#has_quality, http://purl.obolibrary.org/obo/BFO_0000050, http://purl.obolibrary.org/obo/so#overlaps, http://purl.obolibrary.org/obo/fbbt#goslim_synapse, http://purl.obolibrary.org/obo/so#member_of, http://purl.obolibrary.org/obo/go#goslim_candida, http://purl.obolibrary.org/obo/go#goslim_plant, http://purl.obolibrary.org/obo/go#goslim_metagenomics, http://purl.obolibrary.org/obo/go#goslim_pir, http://purl.obolibrary.org/obo/fbbt#goslim_mouse, http://purl.obolibrary.org/obo/go#gocheck_do_not_manually_annotate, http://purl.obolibrary.org/obo/BFO_0000051, http://purl.obolibrary.org/obo/fbbt#gocheck_do_not_manually_annotate, http://purl.obolibrary.org/obo/fbbt#deprecated, http://purl.obolibrary.org/obo/go#goslim_yeast, http://purl.obolibrary.org/obo/fbbt#goslim_plant, http://purl.obolibrary.org/obo/go#gocheck_do_not_annotate, http://purl.obolibrary.org/obo/fbbt#goslim_metagenomics, http://www.w3.org/2002/07/owl#deprecated, http://purl.obolibrary.org/obo/so#has_quality, http://purl.obolibrary.org/obo/go#goslim_agr, http://purl.obolibrary.org/obo/fbbt#goslim_chembl, http://purl.obolibrary.org/obo/so#has_part, http://purl.obolibrary.org/obo/fbbt#goslim_candida, http://purl.obolibrary.org/obo/fbbt#goslim_generic, http://purl.obolibrary.org/obo/go#goslim_mouse, http://purl.obolibrary.org/obo/fbbt#goslim_agr, http://purl.obolibrary.org/obo/so#exemplar_of, http://purl.obolibrary.org/obo/so#contains
	at ebi.spot.neo4j2owl.N2OManager.checkUniqueSafeLabel(N2OManager.java:284)
	at ebi.spot.neo4j2owl.OWL2OntologyImporter.extractSignature(OWL2OntologyImporter.java:458)
	at ebi.spot.neo4j2owl.OWL2OntologyImporter.owl2Import(OWL2OntologyImporter.java:145)
```

For better readability:

- http://purl.obolibrary.org/obo/go#goslim_aspergillus
- http://purl.obolibrary.org/obo/fbbt#goslim_pir
- http://purl.obolibrary.org/obo/go#goslim_pombe
- http://purl.obolibrary.org/obo/fbbt#goslim_pombe
- http://purl.obolibrary.org/obo/go#goslim_generic
- http://purl.obolibrary.org/obo/fbbt#goslim_aspergillus
- http://purl.obolibrary.org/obo/fbbt#gocheck_do_not_annotate
- http://purl.obolibrary.org/obo/so#part_of
- http://purl.obolibrary.org/obo/RO_0002350
- http://purl.obolibrary.org/obo/fbbt#goslim_yeast
- http://purl.obolibrary.org/obo/RO_0002131
- http://purl.obolibrary.org/obo/RO_0001019
- http://purl.obolibrary.org/obo/go#goslim_chembl
- http://purl.obolibrary.org/obo/go#goslim_synapse
- http://purl.obolibrary.org/obo/c099d9d6-4ef3-11e3-9da7-b1ad5291e0b0
- http://purl.obolibrary.org/obo/fbbt#has_quality
- http://purl.obolibrary.org/obo/BFO_0000050
- http://purl.obolibrary.org/obo/so#overlaps
- http://purl.obolibrary.org/obo/fbbt#goslim_synapse
- http://purl.obolibrary.org/obo/so#member_of
- http://purl.obolibrary.org/obo/go#goslim_candida
- http://purl.obolibrary.org/obo/go#goslim_plant
- http://purl.obolibrary.org/obo/go#goslim_metagenomics
- http://purl.obolibrary.org/obo/go#goslim_pir
- http://purl.obolibrary.org/obo/fbbt#goslim_mouse
- http://purl.obolibrary.org/obo/go#gocheck_do_not_manually_annotate
- http://purl.obolibrary.org/obo/BFO_0000051
- http://purl.obolibrary.org/obo/fbbt#gocheck_do_not_manually_annotate
- http://purl.obolibrary.org/obo/fbbt#deprecated
- http://purl.obolibrary.org/obo/go#goslim_yeast
- http://purl.obolibrary.org/obo/fbbt#goslim_plant
- http://purl.obolibrary.org/obo/go#gocheck_do_not_annotate
- http://purl.obolibrary.org/obo/fbbt#goslim_metagenomics
- http://www.w3.org/2002/07/owl#deprecated
- http://purl.obolibrary.org/obo/so#has_quality
- http://purl.obolibrary.org/obo/go#goslim_agr
- http://purl.obolibrary.org/obo/fbbt#goslim_chembl
- http://purl.obolibrary.org/obo/so#has_part
- http://purl.obolibrary.org/obo/fbbt#goslim_candida
- http://purl.obolibrary.org/obo/fbbt#goslim_generic
- http://purl.obolibrary.org/obo/go#goslim_mouse
- http://purl.obolibrary.org/obo/fbbt#goslim_agr
- http://purl.obolibrary.org/obo/so#exemplar_of
- http://purl.obolibrary.org/obo/so#contains

Do you want to 

1) Manually handle them?
2) Use qualified safe labels whenever a safe label is not unique

Thanks!

**Comment by matentzn** [comment]
I vote for 2) as a general method (so that the plugin works in general), but we should strive for 1 in the KB case, and perhaps even let it fail hard when there are conflicting safe labels..
